### ISSUE TITLE
Inconsistency between dl.readme and yaml-loading the readme text when interpreting floats

### ISSUE THREAD

**Issue by AntoineSIMTEK** [IMTEK-Simulation/dtool-lookup-api#24]
I started using dl.readme because it is faster, but with some little bad surprises.

```python
!dtool readme show s3://frct-simdata/901f5d2d-c74f-480f-89e4-c11e55a4bc5f
```
---

should_be_float_but_isnt: 1e-4
ok_1: 1.e-4
ok_2: 0.0001

```python
import dtool_lookup_api.nested as dl
dl.readme("s3://frct-simdata/901f5d2d-c74f-480f-89e4-c11e55a4bc5f")
```
{'ok_1': 0.0001, 'ok_2': 0.0001, 'should_be_float_but_isnt': '1e-4'}
```python
from ruamel.yaml import YAML
yaml = YAML()
yaml.explicit_start = True
yaml.indent(mapping=2, sequence=4, offset=2)
dataset = dtoolcore.DataSet.from_uri("s3://frct-simdata/901f5d2d-c74f-480f-89e4-c11e55a4bc5f")
readme_str = dataset.get_readme_content()
readme_dict = yaml.load(readme_str)
readme_dict
```
ordereddict([('should_be_float_but_isnt', 0.0001), ('ok_1', 0.0001), ('ok_2', 0.0001)])

This isn't dramatic but is good to be aware of. I.e. one should always use the dot in scientific notation.

**Comment by jotelha** [comment]
Thanks, good to have that pointed out, there will certainly be quite a few other inconsistencies like that, and the reason does not lie within this thin query wrapper. When querying stuff from the server, it obviously all comes out of the server's database, and has gone through 
1) the specific storage broker, 
2) server-side README YAML parsing, https://github.com/jic-dtool/dtool-lookup-server/blob/fc5ed28504eafb4e5d1f279897eb722f7a929b12/dtool_lookup_server/utils.py#L189-L227 
3) insertion into database, https://github.com/jic-dtool/dtool-lookup-server/blob/fc5ed28504eafb4e5d1f279897eb722f7a929b12/dtool_lookup_server/utils.py#L664-L702 
4) retrieval from database, https://github.com/jic-dtool/dtool-lookup-server/blob/fc5ed28504eafb4e5d1f279897eb722f7a929b12/dtool_lookup_server/utils.py#L748-L774, 
5) dump as JSON, https://github.com/jic-dtool/dtool-lookup-server/blob/fc5ed28504eafb4e5d1f279897eb722f7a929b12/dtool_lookup_server/dataset_routes.py#L142-L167, 
6) transmission via http, 
7) load from JSON in this API, https://github.com/IMTEK-Simulation/dtool-lookup-api/blob/fe7a80de63c736bbef548366820e731a19b58590/dtool_lookup_api/core/LookupClient.py#L112-L123,

whereas reading the reame directly only involves the first two steps in this pipeline, i.e. getting the readme content via the storage broker and parsing YAML. I don't think its worth going into the subtle format translation inconsistencies from file -> YAML -> mongo BSON -> JSON -> YAML. One other annoying case in that line is the handling of dates, we have discussed about that before, @AntoineSIMTEK, I put a (German language) quote of our chat here to have it documented,

In short, queries like
```
dl.query(
{
"$and":[
 {"readme.owners.name":{"$eq":"Antoine Sanner"}},
 {"frozen_at":{"$gt": 16273}},
],
})
```
on `frozen_at` and `created_at` (represented as Date objects server-side database-internally) won't work.


> Ok, ich habe in den Code vom Server reingesehen, das ist wohl ein Problem, das sich nicht ganz einfach lösen lässt. Kurze Erläuterung: Die DB verwendet intern ein eigenes Format, um Daten abzulegen, das darübergelegte Python-Interface PyMongo verwendet datetime.datetime-Objekte, um mit Daten umzugehen, und der Lookup-Server konvertiert beim Indizieren der Datensätze "frozen_at" und "created_at" explizit in dieses Format, https://github.com/jic-dtool/dtool-lookup-server/blob/fc5ed28504eafb4e5d1f279897eb722f7a929b12/dtool_lookup_server/utils.py#L664-L702 . Die datetime-Objekte sind unglücklicherweise nicht einfach (de-)serialisierbar, d.h. wenn da die Anfrage als einfacher JSON-String per query über REST-API versandt wird, dann lassen sich keine Vergleiche gegen diese Datenobjekte formulieren. Ich muss mir das bei Gelegenheit genauer ansehen.
>
> Was funktionieren sollte, ist gegen die als Strings in der README abgelegten Daten zu vergleichen, also z.B bei dir
```ipython
In [46]: res = dl.query({
    ...: "$and":[
    ...:  {"readme.owners.name":{"$eq":"Antoine Sanner"}},
    ...:  {"readme.creation_date":{"$gt": "2020"}},
    ...: ],
    ...: })

In [47]: len(res)
Out[47]: 2659

In [48]: res = dl.query({
    ...: "$and":[
    ...:  {"readme.owners.name":{"$eq":"Antoine Sanner"}},
    ...:  {"readme.creation_date":{"$gt": "2021"}},
    ...: ],
    ...: })

In [49]: len(res)
Out[49]: 2361
```

**Comment by jotelha** [comment]
In short, the conclusion should be to always access datasets and metadata as direct as possible and use the server only for (sophisticated) searching, but don't use data from the server for further processing where it's avoidable, agreed?

**Comment by AntoineSIMTEK** [comment]
Agreed, thank you for the detailed answer. Now I understand why these readmes can look different.

I suggest to add the label wontfix to the issue
