### ISSUE TITLE
`ConfigurationBasedLookupClient` complains that `DTOOL_LOOKUP_SERVER_URL` is missing

### ISSUE THREAD

**Issue by pastewka** [IMTEK-Simulation/dtool-lookup-api#7]
`ConfigurationBasedLookupClient` complains that `DTOOL_LOOKUP_SERVER_URL` is missing even though the URL is passed in the constructor of the client.

**Comment by jotelha** [comment]
What happens is that https://github.com/IMTEK-Simulation/dtool-lookup-api/blob/master/dtool_lookup_api/core/config.py provides a `Config` object that is created once when imported for the first time (similar to what the lookup server does on the  other end, https://github.com/jic-dtool/dtool-lookup-server/blob/master/dtool_lookup_server/config.py#L17). The warning is generated there at construction no matter whether the user actually intends to use the DTOOL_LOOKUP_SERVER_URL or not, thus the issue should not be specific to `ConfigurationBasedLookupClient`, i.e.

```console
$ ipython
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import logging

In [2]: logging.basicConfig(level=logging.DEBUG)

In [3]: logger = logging.getLogger()
   ...: logger.setLevel(logging.DEBUG)

In [4]: import dtool_lookup_api
WARNING:dtool_lookup_api.core.config:Please provide DTOOL_LOOKUP_SERVER_URL
DEBUG:dtool_lookup_api.core.config:dtool config lookup_url: None
DEBUG:dtool_lookup_api.core.config:dtool config auth_url: 
DEBUG:dtool_lookup_api.core.config:dtool config username: None
DEBUG:dtool_lookup_api.core.config:dtool config verify_ssl: True
```
This https://github.com/IMTEK-Simulation/dtool-lookup-api/commit/f591ef292e3555d534e6833ac28ffca05929cc81 should remove the irrelevant warning.
